wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.16
    start_time: 1677535598.581912
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.16
      5: 0.13.10
      8:
      - 1
      - 2
      - 4
      - 5
